version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - app

  app:
    build: .
    expose:
      - 3031
    restart: on-failure
    environment:
      TRIAL_IMAGE: /app/trial.png
    env_file:
      - .env
    entrypoint: uwsgi uwsgi.ini
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://nginx/"]
      interval: 15s
      timeout: 30s
      retries: 10
      start_period: 15s
    sysctls:
      net.core.somaxconn: 4096

  mysql:
    image: mysql:8.0.27
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: db
    env_file:
      - .env
    restart: always
    platform: linux/x86_64
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 40s 